bundler_args: --without benchmark:development
script: script/cibuild
cache: bundler
language: ruby

rvm:
  - &ruby1 2.7.1
  - &ruby2 2.5.8
  - &jruby jruby-9.2.11.1

matrix:
  include:
    - rvm: *ruby1
      env: TEST_SUITE=fmt
      name: "ðŸ¤–ï¸ Code Format"
    - rvm: *ruby1
      env: TEST_SUITE=default-site
      name: "ðŸ ï¸ Default Site"
    - rvm: *ruby1
      env: TEST_SUITE=profile-docs
      name: "Profile Docs"
    - rvm: *ruby2
      env: TEST_SUITE=memprof
      name: "Profile Memory Allocation"
  exclude:
    - rvm: *jruby
      env: TEST_SUITE=cucumber

env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
branches:
  only:
    - master
    - themes
    - /.*-stable/

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
  slack:
    secure: "\
      dNdKk6nahNURIUbO3ULhA09/vTEQjK0fNbgjVjeYPEvROHgQBP1cIP3AJy8aWs8rl5Yyow4Y\
      GEilNRzKPz18AsFptVXofpwyqcBxaCfmHP809NX5PHBaadydveLm+TNVao2XeLXSWu+HUNAY\
      O1AanCUbJSEyJTju347xCBGzESU=\
    "

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
