bundler_args: --without benchmark:site:development
script: script/cibuild
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.5.1
  - &ruby2 2.4.4
  - &ruby3 2.3.7
  - &jruby jruby-9.1.16.0

env:
  matrix:
    - TEST_SUITE=default-site
branches:
  only:
    - master
    - themes
    - /*-stable/

notifications:
  slack:
    secure: "\
      dNdKk6nahNURIUbO3ULhA09/vTEQjK0fNbgjVjeYPEvROHgQBP1cIP3AJy8aWs8rl5Yyow4Y\
      GEilNRzKPz18AsFptVXofpwyqcBxaCfmHP809NX5PHBaadydveLm+TNVao2XeLXSWu+HUNAY\
      O1AanCUbJSEyJTju347xCBGzESU=\
    "

addons:
  code_climate:
    repo_token:
      secure: "\
        mAuvDu+nrzB8dOaLqsublDGt423mGRyZYM3vsrXh4Tf1sT+L1PxsRzU4gLmcV27HtX2Oq9\
        DA4vsRURfABU0fIhwYkQuZqEcA3d8TL36BZcGEshG6MQ2AmnYsmFiTcxqV5bmlElHEqQuT\
        5SUFXLafgZPBnL0qDwujQcHukID41sE=\
      "

before_install:
  - gem update --system
  - gem install bundler
