language: ruby
before_install:
  - gem install bundler
env: COVERAGE=true
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
script: bundle exec rake
notifications:
  irc:
    channels:
      - "irc.freenode.org#jekyll"
    #on_success: change
    #on_failure: change
    template:
      - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
  email:
    on_success: never
    on_failure: never
