bundler_args: --without benchmark:site:development
script: script/cibuild
cache: bundler
language: ruby
sudo: false

rvm:
  - &ruby1 2.5.0
  - &ruby2 2.4.3
  - &ruby3 2.3.6
  - &ruby4 2.2.9
  - &jruby jruby-9.1.15.0

matrix:
  include:
    - rvm: *ruby1
      env: TEST_SUITE=fmt
    - rvm: *ruby1
      env: TEST_SUITE=default-site
    - rvm: *ruby1
      env: ROUGE_VERSION=1.11.1 # runs everything with this version
  exclude:
    - rvm: *jruby
      env: TEST_SUITE=cucumber

env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
branches:
  only:
    - master
    - themes
    - /*-stable/

notifications:
  slack:
    secure: "\
      dNdKk6nahNURIUbO3ULhA09/vTEQjK0fNbgjVjeYPEvROHgQBP1cIP3AJy8aWs8rl5Yyow4Y\
      GEilNRzKPz18AsFptVXofpwyqcBxaCfmHP809NX5PHBaadydveLm+TNVao2XeLXSWu+HUNAY\
      O1AanCUbJSEyJTju347xCBGzESU=\
    "

addons:
  code_climate:
    repo_token:
      secure: "\
        mAuvDu+nrzB8dOaLqsublDGt423mGRyZYM3vsrXh4Tf1sT+L1PxsRzU4gLmcV27HtX2Oq9\
        DA4vsRURfABU0fIhwYkQuZqEcA3d8TL36BZcGEshG6MQ2AmnYsmFiTcxqV5bmlElHEqQuT\
        5SUFXLafgZPBnL0qDwujQcHukID41sE=\
      "
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter

before_install:
  - gem update --system
