bundler_args: --without benchmark:site:development
before_script: bundle update
script: script/cibuild
cache: bundler
language: ruby
sudo: false

rvm:
- 2.0.0-p648
- 2.1.8
- 2.2.4
- 2.3.0
- jruby-9.0.4.0
- ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-9.0.4.0
    - rvm: ruby-head
env:
  matrix:
  - TEST_SUITE=test
  - TEST_SUITE=cucumber

branches:
  only:
  - master

notifications:
  irc:
    template: "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
    channels: irc.freenode.org#jekyll

  email:
    recipients:
      - jordon@envygeeks.io

  slack:
    secure: "\
      dNdKk6nahNURIUbO3ULhA09/vTEQjK0fNbgjVjeYPEvROHgQBP1cIP3AJy8aWs8rl5Yyow4Y\
      GEilNRzKPz18AsFptVXofpwyqcBxaCfmHP809NX5PHBaadydveLm+TNVao2XeLXSWu+HUNAY\
      O1AanCUbJSEyJTju347xCBGzESU=\
    "

addons:
  code_climate:
    repo_token:
      secure: "\
        mAuvDu+nrzB8dOaLqsublDGt423mGRyZYM3vsrXh4Tf1sT+L1PxsRzU4gLmcV27HtX2Oq9\
        DA4vsRURfABU0fIhwYkQuZqEcA3d8TL36BZcGEshG6MQ2AmnYsmFiTcxqV5bmlElHEqQuT\
        5SUFXLafgZPBnL0qDwujQcHukID41sE=\
      "
