version: "{build}"
image: Visual Studio 2019
build: off

clone_depth: 5

branches:
  only:
    - master
    - themes
    - /.*-stable$/

environment:
  BUNDLE_WITHOUT: "benchmark:development"
  matrix:
    - RUBY_FOLDER_VER: "27"
      TZINFO_VERSION: "~> 1.2"
      TEST_SUITE: "test"
    - RUBY_FOLDER_VER: "27"
      TZINFO_VERSION: "~> 2.0"
      TEST_SUITE: "test"
    - RUBY_FOLDER_VER: "27"
      TEST_SUITE: "default-site"
    - RUBY_FOLDER_VER: "27"
      TEST_SUITE: "profile-docs"
    - RUBY_FOLDER_VER: "27"
      TEST_SUITE: "memprof"
    - RUBY_FOLDER_VER: "27"
      TZINFO_VERSION: "~> 1.2"
      TEST_SUITE: "cucumber"
    - RUBY_FOLDER_VER: "27"
      TZINFO_VERSION: "~> 2.0"
      TEST_SUITE: "cucumber"

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%-x64\bin;%PATH%
  - bundle config set --local clean 'true'
  - bundle config set --local path 'vendor\bundle'
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS%

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bash ./script/cibuild

cache:
  # If one of the files after the right arrow changes, cache will be invalidated
  - 'vendor\bundle -> appveyor.yml,Gemfile,jekyll.gemspec'
