version: "{build}"

clone_depth: 5

branches:
  only:
    - master
    - themes
    - /.*-stable/

build: off

environment:
  BUNDLE_WITHOUT: "benchmark:development"
  matrix:
    - RUBY_FOLDER_VER: "26"
      TEST_SUITE: "test"
    - RUBY_FOLDER_VER: "26"
      TEST_SUITE: "cucumber"
    - RUBY_FOLDER_VER: "26"
      TEST_SUITE: "default-site"
    - RUBY_FOLDER_VER: "26"
      TEST_SUITE: "profile-docs"
    - RUBY_FOLDER_VER: "24"
      TEST_SUITE: "test"

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%-x64\bin;%PATH%
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS% --clean --path vendor\bundle

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bash ./script/cibuild

cache:
  # If one of the files after the right arrow changes, cache will be invalidated
  - 'vendor\bundle -> appveyor.yml,Gemfile,jekyll.gemspec'
