markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true

name: Jekyll â€¢ Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: http://jekyllrb.com

gems:
  - jekyll-feed
