name: Continuous Integration

on:
  push:
    branches:
    - 4.2-stable
  pull_request:
    branches:
    - 4.2-stable

jobs:
  ci:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    name: 'Ruby ${{ matrix.ruby_version }}'
    runs-on: 'ubuntu-latest'
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
        - 2.5
        - 2.7
        - jruby-9.2.11.1
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: "Set up Ruby ${{ matrix.ruby_version }}"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run Unit Tests
      run: bash script/test
    - name: Run Cucumber Features
      run: bash script/cucumber
    - name: Sanity Check
      run: bash script/default-site

  style_check:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    name: 'Code Style Check (Ruby ${{ matrix.ruby_version }})'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
        - 2.5
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: "Set up Ruby ${{ matrix.ruby_version }}"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run RuboCop
      run: bash script/fmt

  profile_docs:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    name: 'Profile Docs Site (Ruby ${{ matrix.ruby_version }})'
    runs-on: 'ubuntu-latest'
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
        - 2.5
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: "Set up Ruby ${{ matrix.ruby_version }}"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Build Docs site with --profile
      run: bash script/profile-docs
    - name: Profile memory usage of building Docs site
      run: bash script/memprof
